version: '3.9'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    ports:
      - '3310:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ma_db
