version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
     - "3600:8080"
    volumes:
      - ./src/:/go/src
    tty: true
    stdin_open: true
    environment:
      MYSQL_DATABASE: go_db
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PW: root
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3382:3306'
    volumes:
      - data-dev:/var/lib/mysql
  front:
    build:
      context: front
    volumes:
      - ./front:/app
    ports:
      - '3005:3000'
      
volumes:
  data-dev:
    driver: local
