version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
     - "3600:8080"
    volumes:
      - ./src/:/go/src
    tty: true
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3382:3306'
  front:
    build:
      context: front
    volumes:
      - ./front:/app
    ports:
      - '3005:3000'
      
