import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Layout from '../components/layouts/layout'

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>ecforce ma</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            ecforce ma / 4knowledge
          </h1>

          <p className={styles.description}>
            This ecforce BI/MA tool.
          </p>

          <div className={styles.grid}>
            <Link href="/objects/">
              <a className={styles.card}>
                <h2>オブジェクト管理 &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </Link>

            <Link href="#">
              <a  className={styles.card}>
                <h2>セグメント管理 &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </a>
            </Link>

            <Link href="#">
              <a className={styles.card}>
                <h2>レポート管理 &rarr;</h2>
                <p>Discover and deploy boilerplate example Next.js projects.</p>
              </a>
            </Link>

            <Link href="#">
              <a className={styles.card}>
                <h2>Deploy &rarr;</h2>
                <p>
                  Instantly deploy your Next.js site to a public URL with Vercel.
                </p>
              </a>
            </Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  )
}

export default Home
